-- Seed 0005 — how to actually perform each exercise.
--
-- `instructions` and `common_mistakes` have been columns since migration 0008
-- and empty since. This fills them.
--
-- Two notes on what is here and what is not.
--
-- The cues are SETUP AND EXECUTION, not physiology. "Touch the chest under
-- control" is checkable by the person doing it; "maximise mechanical tension"
-- is not, and cueing someone with a mechanism they cannot observe is how form
-- advice becomes noise. The mistakes are the ones that actually show up in a
-- gym, ordered by how often.
--
-- `video_url` is deliberately left null. Hard-coding YouTube ids would put the
-- app's authority behind links that rot the first time a channel is deleted or
-- an id is mistyped, and a confidently wrong demonstration is worse than none.
-- The app falls back to a Shorts-filtered search for the exact exercise name
-- instead — see `demoFor` in src/domain/training/exerciseMedia.ts. Set the
-- column on any row where a specific clip has actually been checked; the UI
-- picks it up automatically and labels it as vouched-for rather than found.

update public.exercises as e
set instructions    = v.instructions,
    common_mistakes = v.common_mistakes
from (values

-- --------------------------------------------------------------------- push
('barbell_bench_press',
 array['Lie back with the eyes under the bar; pull the shoulder blades together and down into the bench.',
       'Plant both feet and keep a small natural arch in the lower back.',
       'Unrack, bring the bar over the lower chest, and lower under control until it touches.',
       'Press back up and slightly towards the face, keeping the shoulder blades pinned.'],
 array['Flaring the elbows to 90 degrees, which loads the shoulder joint instead of the chest.',
       'Bouncing the bar off the ribcage to get out of the bottom.',
       'Letting the hips leave the bench to shorten the range of motion.']),

('dumbbell_bench_press',
 array['Sit with the dumbbells on the thighs, then kick them back one at a time as you lie down.',
       'Set the shoulder blades back and down before the first rep.',
       'Lower until the hands are roughly level with the chest and you feel a stretch.',
       'Press up and slightly together, stopping short of clashing the dumbbells.'],
 array['Lowering too far and letting the shoulders roll forward at the bottom.',
       'Pressing the dumbbells together hard at the top, which unloads the chest.',
       'Dropping the weights to the floor instead of returning them to the thighs.']),

('incline_dumbbell_press',
 array['Set the bench to about 30 degrees — steeper turns this into a shoulder press.',
       'Kick the dumbbells up and set the shoulder blades back before starting.',
       'Lower to the upper chest until you feel a stretch across the collarbones.',
       'Press up without letting the elbows drift behind the torso.'],
 array['Using a 45 degree or steeper bench and wondering why the front delts do the work.',
       'Letting the hips slide up to turn it into a flat press.',
       'Shortening the bottom of the rep, which is the part the incline is for.']),

('machine_chest_press',
 array['Set the seat so the handles line up with the middle of the chest.',
       'Sit back firmly with the shoulder blades against the pad.',
       'Press out until the arms are almost straight, without locking hard.',
       'Return under control until you feel a stretch, then press again.'],
 array['A seat set too high, which turns the movement into an incline press.',
       'Letting the shoulders round forward off the pad at the end of a set.',
       'Slamming the weight stack on the way back.']),

('push_up',
 array['Hands slightly wider than the shoulders, directly under them at the bottom.',
       'Squeeze the glutes and brace the abs so the body is one straight line.',
       'Lower until the chest is a fist off the floor, elbows around 45 degrees.',
       'Press back up without letting the hips sag or pike.'],
 array['Hips sagging, which turns it into a lower-back exercise.',
       'Only going halfway down.',
       'Letting the head travel first while the chest stays high.']),

('cable_fly',
 array['Set the pulleys around chest height and take a short staggered stance.',
       'Keep a soft, fixed bend in the elbows for the whole set.',
       'Bring the hands together in front of the chest in an arc, not a press.',
       'Let the hands travel back until you feel a clear stretch, then reverse.'],
 array['Bending and straightening the elbows, which makes it a press.',
       'Going so heavy that the torso swings to start each rep.',
       'Cutting the stretch short, which is the part a press cannot give you.']),

('overhead_press',
 array['Bar on the front delts, hands just outside shoulder width, elbows slightly in front.',
       'Squeeze the glutes and brace the abs so the ribs stay down.',
       'Press up, moving the head back slightly so the bar clears the face.',
       'Finish with the bar over the middle of the foot, then lower under control.'],
 array['Leaning back to move the bar, which turns it into a standing incline press.',
       'Pressing around the face instead of moving the head out of the way.',
       'Losing the brace so the lower back takes the load.']),

('dumbbell_shoulder_press',
 array['Sit with the back supported and the dumbbells at shoulder height.',
       'Keep the elbows slightly in front of the torso rather than straight out to the sides.',
       'Press up until the arms are nearly straight, without clashing the weights.',
       'Lower until the upper arms are roughly parallel to the floor.'],
 array['Flaring the elbows dead sideways, which stresses the shoulder joint.',
       'Arching the lower back off the pad to help the last reps.',
       'Bouncing out of the bottom.']),

-- --------------------------------------------------------------------- pull
('barbell_row',
 array['Hinge at the hips until the torso is around 45 degrees, knees softly bent.',
       'Take a shoulder-width grip and let the bar hang with the arms straight.',
       'Pull towards the belly button, leading with the elbows.',
       'Lower under control until the arms are straight again.'],
 array['Standing up as the set gets hard, which shortens the range and loads the back.',
       'Pulling to the chest instead of the stomach.',
       'Letting the lower back round — stop the set when it does.']),

('dumbbell_row',
 array['Brace one hand and knee on a bench with a flat back.',
       'Let the dumbbell hang and feel the lat stretch at the bottom.',
       'Pull towards the hip, keeping the elbow close to the body.',
       'Lower all the way down before the next rep.'],
 array['Rotating the torso to throw the weight up.',
       'Pulling to the shoulder, which turns it into a rear-delt row.',
       'Stopping short at the bottom and skipping the stretch.']),

('seated_cable_row',
 array['Sit with the knees softly bent and the chest tall.',
       'Let the shoulder blades travel forward at the stretch — this part is intentional.',
       'Pull the handle to the stomach, drawing the shoulder blades together.',
       'Return under control, allowing the stretch again.'],
 array['Leaning back and forth to move heavier weight.',
       'Keeping the shoulder blades locked, which removes half the range.',
       'Shrugging at the top, which hands the work to the traps.']),

('chest_supported_row',
 array['Set the pad so the chest is supported and the arms hang freely.',
       'Start with the arms straight and the shoulder blades forward.',
       'Pull with the elbows towards the hips, squeezing the mid-back.',
       'Lower under control to a full stretch.'],
 array['Pushing off the pad with the chest to help the rep.',
       'Cutting the bottom short.',
       'Using so much weight that the head or hips take over.']),

('pull_up',
 array['Grip slightly wider than the shoulders, hanging with the arms straight.',
       'Pull the shoulder blades down before the elbows bend.',
       'Drive the elbows down and back until the chin clears the bar.',
       'Lower all the way to a full hang.'],
 array['Kipping with the legs once the reps get hard.',
       'Stopping halfway down between reps, which skips the stretch.',
       'Shrugging the shoulders up towards the ears at the start of the pull.']),

('lat_pulldown',
 array['Set the thigh pad so the legs are pinned and the hips do not lift.',
       'Take a grip slightly wider than the shoulders and sit tall.',
       'Pull the bar to the upper chest, driving the elbows down.',
       'Return under control until the arms are straight and the shoulders rise slightly.'],
 array['Leaning far back so it becomes a row.',
       'Pulling behind the neck, which stresses the shoulder for no extra benefit.',
       'Letting the weight yank the arms up between reps.']),

-- ---------------------------------------------------------------------- legs
('back_squat',
 array['Bar on the upper back, not the neck; hands just wide enough to be comfortable.',
       'Step out, feet about shoulder width, toes turned slightly out.',
       'Brace, then sit down and slightly back, keeping the knees tracking over the toes.',
       'Descend until the hip crease passes the knee, then drive up through the whole foot.'],
 array['Knees caving inwards on the way up.',
       'The hips shooting up first, which turns it into a good morning.',
       'Rounding the lower back at the bottom — stop the set at the depth where it starts.']),

('front_squat',
 array['Rest the bar on the front delts with the elbows held high.',
       'Keep the torso as upright as possible throughout.',
       'Sit straight down, knees travelling forward over the toes.',
       'Drive up while keeping the elbows from dropping.'],
 array['Letting the elbows drop, which rolls the bar forward off the shoulders.',
       'Gripping the bar with the hands instead of resting it on the shoulders.',
       'Turning it into a back squat by leaning forward.']),

('leg_press',
 array['Set the feet mid-platform, about shoulder width.',
       'Lower until the knees reach roughly 90 degrees or a touch deeper.',
       'Keep the lower back flat against the pad for the whole rep.',
       'Press through the whole foot without snapping the knees straight.'],
 array['Going so deep that the pelvis rolls off the pad at the bottom.',
       'Locking the knees hard at the top.',
       'Pushing with the toes and letting the heels lift.']),

('hack_squat',
 array['Set the shoulders under the pads and the feet mid-platform.',
       'Brace and lower under control, keeping the back flat against the pad.',
       'Descend until the thighs are at least parallel.',
       'Drive up through the whole foot.'],
 array['Cutting the depth short because the machine makes heavy weight easy.',
       'Letting the knees cave in on the drive.',
       'Locking out hard at the top of every rep.']),

('goblet_squat',
 array['Hold a dumbbell or kettlebell against the chest with both hands.',
       'Feet about shoulder width, toes slightly out.',
       'Sit straight down between the feet, keeping the chest up.',
       'Descend until the elbows are inside the knees, then stand up.'],
 array['Letting the weight pull the torso forward.',
       'Rising onto the toes at the bottom.',
       'Treating it as a warm-up and never adding load.']),

('romanian_deadlift',
 array['Stand with the bar at the hips, knees softly bent and fixed there.',
       'Push the hips back and let the bar slide down the thighs.',
       'Stop when the hamstrings are fully stretched, usually mid-shin.',
       'Drive the hips forward to stand, without leaning back at the top.'],
 array['Bending the knees more as it gets hard, which turns it into a deadlift.',
       'Letting the bar drift away from the legs.',
       'Rounding the lower back to reach the floor — the stretch sets the depth, not the floor.']),

('conventional_deadlift',
 array['Bar over mid-foot, shins close, hands just outside the knees.',
       'Take the slack out of the bar, then set the back flat and brace.',
       'Push the floor away and keep the bar against the legs.',
       'Stand tall, then lower by pushing the hips back first.'],
 array['Jerking the bar off the floor before the slack is out.',
       'The hips rising faster than the chest.',
       'Leaning back and hyperextending at the top.']),

('seated_leg_curl',
 array['Set the pad just above the ankles and the thigh pad snug.',
       'Sit back fully so the hips stay flexed — this is what makes it seated.',
       'Curl the heels under as far as they will travel.',
       'Return slowly to a full stretch.'],
 array['Lifting the hips off the seat to help the last reps.',
       'Cutting the return short and never reaching the stretch.',
       'Letting the weight fall back rather than lowering it.']),

('hip_thrust',
 array['Shoulder blades on a bench, bar across the hips with a pad.',
       'Feet flat, roughly shin-vertical at the top of the rep.',
       'Drive through the heels until the torso is parallel to the floor.',
       'Squeeze the glutes at the top without arching the lower back.'],
 array['Hyperextending the lower back at the top instead of finishing with the glutes.',
       'Feet too far forward, which hands the work to the hamstrings.',
       'Bouncing off the floor between reps.']),

('bulgarian_split_squat',
 array['Rear foot on a bench, front foot far enough forward to keep the shin near vertical.',
       'Lower straight down until the back knee is just off the floor.',
       'Keep most of the weight through the front heel.',
       'Drive up without pushing off the back foot.'],
 array['Front foot too close, which grinds the knee forward.',
       'Pushing off the rear leg to help.',
       'Cutting the depth short because balance is the limiting factor — steady yourself instead.']),

('walking_lunge',
 array['Step forward far enough that the front shin stays near vertical.',
       'Lower until the back knee is just off the floor.',
       'Drive through the front heel to stand and step straight into the next rep.',
       'Keep the torso upright throughout.'],
 array['Short steps, which push the knee well past the toes.',
       'Letting the front knee cave inwards on the drive up.',
       'Leaning forward over the front thigh.']),

-- ----------------------------------------------------------------- shoulders
('lateral_raise',
 array['Stand with the dumbbells at the sides, elbows slightly bent.',
       'Raise out to the sides, leading with the elbows.',
       'Stop at about shoulder height.',
       'Lower slowly — the way down is most of the work.'],
 array['Swinging the torso to start each rep.',
       'Going above shoulder height, which brings the traps in.',
       'Going too heavy and turning it into an upright row.']),

('cable_lateral_raise',
 array['Stand side-on to a low pulley and take the handle in the outside hand.',
       'Keep a soft fixed bend in the elbow.',
       'Raise out to shoulder height against the cable.',
       'Lower slowly and let the arm cross slightly in front at the bottom.'],
 array['Leaning away from the machine to help the weight up.',
       'Letting the cable snap the arm back down.',
       'Standing too close, which removes the tension at the bottom.']),

('reverse_fly',
 array['Hinge forward or set a chest pad so the arms hang straight down.',
       'Keep a soft fixed bend in the elbows.',
       'Open the arms out to the sides, leading with the elbows.',
       'Stop level with the torso and lower under control.'],
 array['Bending the elbows to turn it into a row.',
       'Shrugging the shoulders towards the ears.',
       'Using enough weight that the torso rocks each rep.']),

('face_pull',
 array['Set a rope at roughly face height and step back until the cable is taut.',
       'Pull the rope towards the face, splitting the hands apart.',
       'Finish with the hands beside the ears and the elbows high.',
       'Return under control without letting the shoulders roll forward.'],
 array['Pulling to the chest, which makes it a row.',
       'Letting the elbows drop below the shoulders.',
       'Going heavy enough that the lower back leans back to help.']),

-- --------------------------------------------------------------------- arms
('barbell_curl',
 array['Stand with the bar at arms length, hands about shoulder width.',
       'Keep the elbows pinned at the sides.',
       'Curl up without letting the elbows travel forward.',
       'Lower all the way until the arms are straight.'],
 array['Swinging the hips to start the rep.',
       'Letting the elbows drift forward, which turns it into a front raise.',
       'Stopping short at the bottom and cutting the stretch.']),

('dumbbell_curl',
 array['Stand with the dumbbells at the sides, palms facing forward or neutral.',
       'Curl one or both up, keeping the elbows at the sides.',
       'Turn the palm up as you curl if starting neutral.',
       'Lower slowly to a full stretch.'],
 array['Leaning back to help the last few reps.',
       'Shrugging at the top.',
       'Half-repping the bottom.']),

('incline_dumbbell_curl',
 array['Sit back on a bench set to about 45 to 60 degrees.',
       'Let the arms hang straight down behind the torso — this is the point of the incline.',
       'Curl up without letting the elbows travel forward.',
       'Lower all the way back to the stretch.'],
 array['Letting the elbows swing forward, which removes the stretch the incline creates.',
       'Sitting too upright.',
       'Cutting the bottom of the rep short.']),

('cable_pushdown',
 array['Stand close to the pulley with the elbows pinned at the sides.',
       'Start with the forearms roughly parallel to the floor.',
       'Push down until the arms are straight.',
       'Return under control without letting the elbows drift.'],
 array['Leaning over the bar to press with bodyweight.',
       'Letting the elbows travel forward and back.',
       'Flaring the elbows out at the sides.']),

('overhead_cable_extension',
 array['Face away from the pulley with the rope held behind the head.',
       'Keep the upper arms fixed beside the ears.',
       'Extend the elbows until the arms are straight overhead.',
       'Lower under control until a clear stretch is felt.'],
 array['Letting the upper arms drop forward, which turns it into a press.',
       'Arching the lower back to hold the position.',
       'Cutting the stretch, which is what overhead work is for.']),

('dip',
 array['Support yourself on the bars with the arms straight.',
       'Lean the torso slightly forward to bias the chest, or stay upright for triceps.',
       'Lower until the upper arms are roughly parallel to the floor.',
       'Press back up without locking out hard.'],
 array['Dropping too deep, which strains the front of the shoulder.',
       'Bouncing out of the bottom.',
       'Shrugging the shoulders up towards the ears at the bottom.']),

-- -------------------------------------------------------------- calves, core
('standing_calf_raise',
 array['Stand with the balls of the feet on the platform, heels hanging free.',
       'Let the heels drop until a clear stretch is felt.',
       'Rise onto the toes as high as they will go.',
       'Pause briefly at the top, then lower slowly.'],
 array['Bouncing out of the bottom on the tendon rather than the muscle.',
       'Cutting the range at both ends and calling it a rep.',
       'Bending the knees, which brings the soleus in and unloads the target.']),

('seated_calf_raise',
 array['Set the pad snug across the lower thighs.',
       'Balls of the feet on the platform, heels free.',
       'Drop the heels to a full stretch, then push up as high as possible.',
       'Pause at the top and lower under control.'],
 array['Short, fast reps with no pause.',
       'Loading so heavy the range collapses.',
       'Pressing with the hands on the pad.']),

('hanging_leg_raise',
 array['Hang from a bar with the shoulders active, not fully relaxed.',
       'Brace the abs and tilt the pelvis back before lifting.',
       'Raise the legs until the hips are fully flexed.',
       'Lower slowly without letting the body swing.'],
 array['Swinging and using momentum from the backswing.',
       'Only lifting the knees while the pelvis stays still, which makes it a hip flexor exercise.',
       'Dropping the legs and starting the next rep from the swing.']),

('cable_crunch',
 array['Kneel facing the stack with the rope beside the head.',
       'Keep the hips fixed — they should not move at all.',
       'Crunch by rounding the spine and bringing the ribs towards the pelvis.',
       'Return under control until a stretch is felt in the abs.'],
 array['Hinging at the hips instead of flexing the spine.',
       'Pulling with the arms.',
       'Letting the weight drag the torso back up.']),

('plank',
 array['Forearms under the shoulders, feet about hip width.',
       'Squeeze the glutes and brace the abs so the body is one straight line.',
       'Tuck the pelvis slightly so the lower back does not sag.',
       'Breathe normally and hold — end the set when the position breaks, not when time runs out.'],
 array['Hips sagging towards the floor.',
       'Hips piking up into an easier position.',
       'Holding the breath, which makes the number look better than the brace is.']),

('back_extension',
 array['Set the pad just below the hip bones so the hips can move freely.',
       'Cross the arms over the chest or hold a weight there.',
       'Hinge down at the hips with a flat back.',
       'Raise until the body is straight — no further.'],
 array['Hyperextending at the top, which is where this exercise gets its bad reputation.',
       'Rounding the back on the way down.',
       'Swinging up rather than driving with the glutes and hamstrings.'])

) as v(id, instructions, common_mistakes)
where e.id = v.id;
